services:
  nginx:
    container_name: mountaintea-nginx-prod
    restart: always
    networks:
      - localnet
    volumes:
      - media-data:/media-volume
    build:
      context: .
      target: nginx-prod
    depends_on:
      - server
    hostname: nginx

  cf-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: mountaintea-cloudflare-tunnel
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=$CF_TUNNEL_TOKEN
    networks:
      - localnet

  server:
    container_name: mountaintea-server
    env_file: ".env"
    restart: always
    build:
      context: .
      target: prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      - localnet
    hostname: server
    volumes:
      - media-data:/app/mountaintea_band_site/media

  db:
    container_name: mountaintea-db
    image: postgres:17
    env_file: ".env"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-backup-data:/tmp/dumps
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "dummy", "-d", "mountaintea-db" ]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - localnet
    hostname: db
    labels:
      - docker-volume-backup.archive-pre=/bin/sh -c 'pg_dump -U dummy -w mountaintea-db > /tmp/dumps/mountaintea-db.dump'

  backup:
    image: offen/docker-volume-backup:v2
    container_name: mountaintea-backup
    env_file: ".env"
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: '7'
    restart: always
    volumes:
      - media-data:/backup/media-backup:ro
      - db-backup-data:/backup/db-backup:ro
      - ${HOME}/backups:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  db-data:
    name: "mountaintea-db-data"
    external: true
  media-data:
    name: "mountaintea-media-data"
    external: true
  db-backup-data:
    name: "mountaintea-db-backup-data"

networks:
  localnet:
    driver: bridge
