# Generated by Django 3.1.6 on 2021-02-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=models.TextField(verbose_name='Описание концерта'),
        ),
    ]
