# Generated by Django 3.2.7 on 2021-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='max_count',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='price max tickets'),
        ),
    ]
