# Generated by Django 3.2.16 on 2025-01-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_alter_price_max_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='buy_ticket_message',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Сообщение на странице оформления билетов'),
        ),
        migrations.AddField(
            model_name='concert',
            name='email_title',
            field=models.CharField(default='Билет на концерт', max_length=255, verbose_name='theme of email'),
        ),
        migrations.AddField(
            model_name='concert',
            name='promo_email_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='theme of promo email'),
        ),
        migrations.AddField(
            model_name='concert',
            name='yandex_wallet_receiver',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='receiver for yoomoney'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_delivery_code',
            field=models.IntegerField(default=None, null=True, verbose_name='status code of email delivery'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_delivery_message',
            field=models.TextField(default=None, null=True, verbose_name='delivery status message'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_status',
            field=models.CharField(choices=[('unnecessary', 'Транзакция еще не завершена или билет был куплен слишком давно, проверка отправки письма не нужна.'), ('accepted', 'Письмо получено email сервером и поставлено в очередь на отправку.'), ('rejected', 'Письмо не прошло валидацию email сервера, проверьте логи ошибок.'), ('delivered', 'Письмо доставлено и принято сервером получателя.'), ('failed', 'Письмо не доставлено из-за ошибки на сервере получателя.'), ('opened', 'Письмо прочитано получателем.'), ('clicked', 'The email recipient clicked on a link in the email.'), ('unsubscribed', 'The email recipient clicked on the unsubscribe link.'), ('complained', 'The email recipient clicked on the spam complaint button within their email client. Feedback loops enable the notification to be received by Mailgun.'), ('stored', 'Mailgun has stored an incoming message')], default='unnecessary', max_length=12, verbose_name='email send status'),
        ),
    ]
