# Generated by Django 3.1.6 on 2021-02-05 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_auto_20210204_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6)),
                ('price', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='concert.price')),
                ('transaction', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='concert.transaction')),
            ],
        ),
    ]
