# Generated by Django 3.1.6 on 2021-02-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0004_auto_20210207_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
