# Generated by Django 3.1.6 on 2021-09-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0005_auto_20210220_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='template',
            field=models.TextField(default='<p>Добавьте страницу концерта</p>'),
        ),
    ]
