# Generated by Django 3.1.6 on 2021-09-27 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concert', '0006_concert_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='date',
        ),
        migrations.RemoveField(
            model_name='price',
            name='active',
        ),
        migrations.AddField(
            model_name='concert',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='concert date'),
        ),
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('RUB', 'рубль'), ('EUR', 'евро'), ('USD', 'доллар'), ('GBP', 'британский фунт')], default='RUB', max_length=3, verbose_name='price currency'),
        ),
        migrations.AddField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='price active'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=models.TextField(verbose_name='concert description'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='concert active'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='place',
            field=models.CharField(max_length=255, verbose_name='name and address of place'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='place_url',
            field=models.URLField(verbose_name='url to place page'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='template',
            field=models.TextField(default='<p>Добавьте страницу концерта</p>', verbose_name='template to show concert page'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='title',
            field=models.CharField(max_length=255, verbose_name='concert title'),
        ),
        migrations.AlterField(
            model_name='price',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.concert', verbose_name='the related concert'),
        ),
        migrations.AlterField(
            model_name='price',
            name='description',
            field=models.CharField(max_length=255, verbose_name='price description'),
        ),
        migrations.AlterField(
            model_name='price',
            name='max_count',
            field=models.IntegerField(blank=True, default=None, verbose_name='price max tickets'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(verbose_name='price of ticket'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Контактный телефон', max_length=128, region=None, verbose_name="user's phone"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='the related user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is ticket valid'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(max_length=6, unique=True, verbose_name='ticket number'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.price', verbose_name='the related price'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.transaction', verbose_name='the related transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_sum',
            field=models.FloatField(default=None, null=True, verbose_name='amount sum'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.concert', verbose_name='the related concert'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_closed',
            field=models.DateTimeField(default=None, null=True, verbose_name='date close'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date time created'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='the related user'),
        ),
    ]
