# Generated by Django 3.1.6 on 2021-09-27 06:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0007_auto_20210927_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Контактный телефон', max_length=128, null=True, region=None, verbose_name="user's phone"),
        ),
    ]
